### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by jhughesoti** [iot-dsa-v2/dslink-java-v2-bacnet#5]
Dependency in build.gradle file is not available and so cannot be built.

implementation 'com.github.iot-dsa-v2:driver-framework-java-v2-prototype:master-SNAPSHOT'

**Comment by tishma** [comment]
@a-hansen +1 for this one. It's perhaps more like problem in dependency itself, but I've also found it here - trying to track it down.

**Comment by a-hansen** [comment]
I believe this and the driver framework are deprecated although I don't know what is being done to convey that to the public (@ilyatsarev).  If you really want to use them, maybe we can give you guys access to continue them (but I can't make that decision).  In the meantime, if you really want to use it, I recommend building and installing that driver framework to mavenLocal.

**Comment by tishma** [comment]
Shoot. So where are bacnet dslink sources then?

**Comment by a-hansen** [comment]
I think you guys are really looking for https://github.com/IOT-DSA/dslink-java-bacnet2 which was done with the v1 sdk.

**Comment by tishma** [comment]
Gotcha!

**Comment by a-hansen** [comment]
Sorry about the confusion.  We were never happy with calling the new v2 sdk "v2" because we knew this would happen.  It was a political decision which is no longer relevant and the people who made it are gone :-P

**Comment by tishma** [comment]
Clearly, names are not matching for those who (unlike myself) can read, but... It'd be great if you somehow marked this repo as deprecated, just in case someone else goes this path though.
